version: '2'

services:
  elasticsearch:
    hostname: "hostname"
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.2
    container_name: es5.6.2
    volumes:
        - /vlt/elasticsearch/data:/usr/share/elasticsearch/data
        - /vlt/elasticsearch/log:/var/log/elasticsearch
        - /vlt/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - cluster.name=datalab
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms5000m -Xmx5000m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 6g
    network_mode: "host"
  
  cassandra:
    image: cassandra
    container_name: cassandra
    env_file:
      - cassandra_pl.env
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7199:7199"
      - "9042:9042"
      - "9160:9160"
    volumes:
      #- /data/cassandra/config:/etc/cassandra
      - /data/cassandra/data:/var/lib/cassandra
      - /data/cassandra/log:/var/lib/cassandra/commitlog
     # - /data/cassandra/saved_caches:/var/lib/cassandra/saved_caches
    network_mode: "host"














