version: '2'
services:

  grafana:
    image: grafana/grafana:master
    container_name: grafana
    volumes:
      - /data/grafana/grafana.db:/var/lib/grafana/grafana.db
    ports:
      - 3000:3000

  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.2
    container_name: kibana
    volumes:
      - /data/kibana/data:/usr/share/kibana/data
      - /data/kibana/config:/usr/share/kibana/config
      - /data/kibana/logs:/var/log/kibana.log
    ports:
      - "5601:5601"
    network_mode: "host"

  kairosdb:
    build: kairosdb/
    container_name: kairosdb
    volumes:
        - /data/kairosdb/conf:/kairosdb/conf
        - /data/kairosdb/log:/kairosdb/log
    ports:
      - "4242:4242"
#     - "8003:8080"
    network_mode: "host"


              
